### ISSUE TITLE
Android: weird linker issue when running compiled build

### ISSUE THREAD

**Issue by Miepee** [famfo/frogfetch-rs#12]
After compiling with `cargo build --release` and executing `/target/release/frogfetch-rs` I'm getting a weird linker issue:
![grafik](https://user-images.githubusercontent.com/38186597/147419617-c99bb977-495a-45e0-bb50-69e82f0a936e.png)
`WARNING: linker: /data/data/com.termux/files/home/frogfetch-rs/target/release/frogfetch-rs: unsupported flags DT_FLAGS_1=0x8000001`

These don't happen when using `cargo run`.

**Comment by famfo** [comment]
Doesn't happen on my phone. 
Since it doesn't impact the general usage, I'm closing it.

**Comment by Miepee** [comment]
Would still be nice to figure out why it happens tho.
I'll pull again in a few to check if it still happens.
EDIT: still happens
