### ISSUE TITLE
Create AUR package

### ISSUE THREAD

**Issue by Miepee** [famfo/frogfetch-rs#4]
Please create an AUR package. That would be nice.

**Comment by ladysharkyshark** [comment]
why don't you? [Creating packages - Arch Wiki](https://wiki.archlinux.org/title/Creating_packages#Prerequisite_software)

**Comment by Miepee** [comment]
Actually has already been done by karx, so closing issue

**Comment by famfo** [comment]
Yea, there is a bin and git version.

https://aur.archlinux.org/packages/frogfetch-bin/
https://aur.archlinux.org/packages/frogfetch-git/
