### ISSUE TITLE
ANDROID: CPU implementation broken

### ISSUE THREAD

**Issue by Miepee** [famfo/frogfetch-rs#5]
The cpu implementation is broken on Android, as it only displays an empty string.
![image](https://user-images.githubusercontent.com/38186597/147419278-e1d43735-75b8-4073-aa26-373dcc1c48cf.png)

**Comment by famfo** [comment]
The CPU doesn't show up in /proc/cpuinfo on termux, so there is no way to get it (that I know of) in Termux.

**Comment by Miepee** [comment]
It is possible to get the CPU on Android via `getprop ro.config.cpu.info.display` or with `lscpu`.
`/proc/cpuinfo` does show `AArch Processor rev 4 (aarch64)` which I guess is correct, although isn't really the name of the CPU :P

**Comment by famfo** [comment]
`lscpu` seems to work
